"""
Use Twilio to place a call and play the audio generated by Eleven Labs
"""

# Python imports
import tempfile
import os

# External imports
import requests
from twilio.rest import Client

# Internal imports
from voice_agent.elevenlabs import text_to_speech

def upload_audio(audio_bytes: bytes):
    """Upload audio to temporary hosting service and return public URL."""

    # General assertion check
    assert isinstance(audio_bytes, bytes), "audio_bytes must be bytes type"

    # Write audio bytes to a temporary file
    with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
        tmp.write(audio_bytes)
        tmp_path = tmp.name

    # Use tmpfiles.org to upload the data
    try:
        with open(tmp_path, "rb") as f:
            files = {"file": ("audio.mp3", f, "audio/mpeg")}
            resp = requests.post("https://tmpfiles.org/api/v1/upload", files=files)
            resp.raise_for_status()
            data = resp.json()
            if data.get("status") == "success" and "data" in data:
                url = data["data"]["url"].replace("tmpfiles.org/", "tmpfiles.org/dl/")
                return url
        raise Exception(f"Upload failed: {data}")
    finally:
        os.unlink(tmp_path)

def make_call(question):
    """
    Make a voice survey call with all the inputs
    """

    # Get Twilio credentials
    # TODO maybe get these passed in somewhere else somehow?
    sid = os.getenv("TWILIO_ACCOUNT_SID")
    token = os.getenv("TWILIO_AUTH_TOKEN")
    from_num = os.getenv("TWILIO_FROM_NUMBER")
    to_num = os.getenv("TWILIO_TO_NUMBER")

    # Convert to speech using Eleven Labs
    audio_bytes = text_to_speech(question)

    # Upload audio
    audio_url = upload_audio(audio_bytes)

    # Build TwiML
    twiml = f'''<Response>
        <Play>{audio_url}</Play>
        <Record maxLength="120" timeout="5" finishOnKey="#" playBeep="true" />
        <Say>Thank you. Goodbye.</Say>
    </Response>'''

    # Place call
    client = Client(sid, token)
    client.calls.create(to=to_num, from_=from_num, twiml=twiml)
