"""
Use Twilio to place a call and play the audio generated by Eleven Labs
"""

import os

# Internal imports
from eleven_labs_voice import generate_survey_text

audio = generate_survey_text()

# Save audio bytes to a temporary MP3 file so we can host/send it
with NamedTemporaryFile(suffix=".mp3", delete=False) as tf:
    tf.write(audio)
    tmp_path = tf.name

# If Twilio credentials and phone numbers are provided, place a call
twilio_sid = os.getenv("TWILIO_ACCOUNT_SID")
twilio_token = os.getenv("TWILIO_AUTH_TOKEN")
twilio_from = os.getenv("TWILIO_FROM_NUMBER")
twilio_to = os.getenv("TWILIO_TO_NUMBER")

if twilio_sid and twilio_token and twilio_from and twilio_to:
    print("Uploading audio to a temporary public URL via a simple file host (file.io)...")
    # NOTE: In production, host this MP3 on a public URL (S3, CDN) reachable by Twilio.
    # For a quick demo we upload to https://file.io which returns a temporary link.
    try:
        with open(tmp_path, "rb") as f:
            files = {"file": (os.path.basename(tmp_path), f, "audio/mpeg")}
            resp = requests.post("https://file.io", files=files)
            resp.raise_for_status()
            link = resp.json().get("link")
    except Exception as e:
        raise Exception(f"Failed to upload audio to a public URL: {e}")

    print(f"Making Twilio call to {twilio_to} and playing the uploaded audio...")
    tw_client = TwilioClient(twilio_sid, twilio_token)
    # plas the uploaded audio URL
    twiml = f"<Response><Play>{link}</Play></Response>"
    call = tw_client.calls.create(to=twilio_to, from_=twilio_from, twiml=twiml)
    print(f"Call initiated: SID={call.sid}")
